export const data = [
    {
        name: "square",
        text: "正方形",
        width: 100,
        height: 100,
    },
    {
        name: "rectangle",
        text: "矩形",
        width: 100,
        height: 100,
    },
    {
        name: "circle",
        text: "圆",
        width: 100,
        height: 100,
    },
    {
        name: "triangle",
        text: "三角形",
        width: 100,
        height: 100,
    },
    {
        name: "diamond",
        text: "菱形",
        width: 100,
        height: 100,
    },
    {
        name: "pentagon",
        text: "五边形",
        width: 100,
        height: 100,
    },
    {
        name: "pentagram",
        text: "五角星",
        width: 100,
        height: 100,
    },
    {
        name: "hexagon",
        text: "六边形",
        width: 100,
        height: 100,
    },
    {
        name: "leftArrow",
        text: "左箭头",
        width: 100,
        height: 100,
    },
    {
        name: "rightArrow",
        text: "右箭头",
        width: 100,
        height: 100,
    },
    {
        name: "twowayArrow",
        text: "双向箭头",
        width: 100,
        height: 100,
    },
    {
        name: "message",
        text: "消息框",
        width: 100,
        height: 100,
    },
    {
        name: "cloud",
        text: "云",
        width: 100,
        height: 100,
    },
    {
        name: "file",
        text: "文件",
        width: 100,
        height: 100,
    },
    {
        name: "cube",
        text: "立方体",
        width: 100,
        height: 100,
    },
    {
        name: "people",
        text: "人",
        width: 100,
        height: 100,
    },
    {
        name: "line",
        text: "线",
        width: 100,
        height: 100,
    },
    {
        name: "iframe",
        text: "网页",
        width: 100,
        height: 100,
    },
    {
        name: "video",
        text: "音视频",
        width: 100,
        height: 100,
    },
    {
        name: "gif",
        text: "gif 动画",
        width: 100,
        height: 100,
    },
    {
        name: "flowData",
        text: "数据",
        width: 100,
        height: 100,
    },
    {
        name: "flowSubprocess",
        text: "子流程",
        width: 100,
        height: 100,
    },
    {
        name: "flowDb",
        text: "数据库",
        width: 100,
        height: 100,
    },
    {
        name: "flowDocument",
        text: "文档",
        width: 100,
        height: 100,
    },
    {
        name: "flowInternalStorage",
        text: "内部存储",
        width: 100,
        height: 100,
    },
    {
        name: "flowQueue",
        text: "队列",
        width: 100,
        height: 100,
    },
    {
        name: "flowManually",
        text: "手动输入",
        width: 100,
        height: 100,
    },
    {
        name: "flowDisplay",
        text: "展示",
        width: 100,
        height: 100,
    },
    {
        name: "flowParallel",
        text: "并行模式",
        width: 100,
        height: 100,
    },
    {
        name: "flowComment",
        text: "注释",
        width: 100,
        height: 100,
    },
    {
        name: "activityFinal",
        text: "结束",
        width: 100,
        height: 100,
    },
    {
        name: "swimlaneV",
        text: "垂直泳道",
        width: 100,
        height: 100,
    },
    {
        name: "swimlaneH",
        text: "水平泳道",
        width: 100,
        height: 100,
    },
    {
        name: "forkV",
        text: "垂直分岔/汇合",
        width: 100,
        height: 100,
    },
    {
        name: "forkH",
        text: "水平分岔/汇合",
        width: 100,
        height: 100,
    },
    {
        name: "lifeline",
        text: "生命线",
        width: 100,
        height: 100,
    },
    {
        name: "sequenceFocus",
        text: "激活",
        width: 100,
        height: 100,
    },
    {
        name: "simpleClass",
        text: "简单类图",
        width: 100,
        height: 100,
    },
    {
        name: "interfaceClass",
        text: "普通类图",
        width: 100,
        height: 100,
    },
    {
        name: "echarts",
        width: 400,
        height: 300
      }
]